### ISSUE TITLE
in is a reserved word in javascript

### ISSUE THREAD

**Issue by ManfredGruber** [jeremenichelli/hunt#11]
Hi Jeremias,
this is a great plugin - THANK YOU for that!

There is just one problem for me - **"in"** is a reserved word in javascript, see http://www.w3schools.com/js/js_reserved.asp for a complete list of reserved words.

I would suggest to change ...
Hunted.prototype.**in** = function() {};
... to ..
Hunted.prototype.**inscrolled** = function() {}; 

consequently Hunted.prototype.out should then be renamed to Hunted.prototype.outscrolled

Manfred

**Comment by jeremenichelli** [comment]
Thanks for the report. Still working on that name, I wasn't actually happy with `in` but didn't have another idea. We'll come back with a solution.

**Comment by msfragala** [comment]
We think of the elements as _entering_ or _exiting_ the viewport, so I think that `enter` and `exit` would be good candidates.

**Comment by jeremenichelli** [comment]
@msfragala that's a good call, seriously sorry guys for taking so long to solve this but I just can't decide on two new words for this.

**Comment by ManfredGruber** [comment]
Hi, **_enter_** and **_exit_** are good suggestions, when will there be a new version of hunt?

**Comment by jeremenichelli** [comment]
Sorry for the long wait everyone, the `in` method has been changed to `enter`, everything else remains the same.

**Comment by ManfredGruber** [comment]
works perfect - THANK YOU!
