### ISSUE TITLE
Unbind

### ISSUE THREAD

**Issue by nlemoine** [jeremenichelli/hunt#12]
Hi, 

It would be great to provide a way to unbind events. It's actually nearly impossible to remove the events binded by hunt.

**Comment by jeremenichelli** [comment]
Would you wish to call *hunt* inside your own listeners and have control about them or just disconnect it at some point?

Also, what are your main concerns? Performance?

**Comment by nlemoine** [comment]
Actually, in a responisve context, I'd like to disable hunt on small devices (scroll isn't handled very well on most touch devices). 

A very simple and cheap way to achive this would be to namespace your event names such as: scroll.hunt for example.

**Comment by jeremenichelli** [comment]
Don't know if it's exactly what you were lloking for, but right now the library doesn't hunt elements if it's not called and listeners are not added. Also if you haven't used `persist: true` and all your elements have been _hunted_, listeners are remove to avoid unnecessary operations in **v2.0.0**.

If you don't even want to hunt elements just add a condition like:
```
if (!isMobile) {
  hunt(document.querySelector('.some__element'), {
    enter: function() {
        this.classList.add('visible');
    }
  });
}
```
