### ISSUE TITLE
Remove a hunted element

### ISSUE THREAD

**Issue by axelhzf** [jeremenichelli/hunt#14]
I have look at the source and it seems that there is no way to remove a hunted element.

The API could be something like this

```js
var removeHuntElement = hunt(document.getElementsByClassName('element'), {
    enter: function() {
        this.classList.add('visible');
    }
}

removeHuntElement()
```

I can make a PR if it looks good to you

**Comment by jeremenichelli** [comment]
No way to remove, though if you use `persist: true` after it has become visible and goes out the script removes it from the observed elements.

Can you explain in which situtaiton this couldn't be enough?

**Comment by jeremenichelli** [comment]
Makes sense, don't know if it's convenient to pick which element to remove, but at least a way to shut down the _hunting_ process. I'll work on this.

**Comment by jeremenichelli** [comment]
@axelhzf sorry for the delay my friend, you can now call `hunt.clear()` at any time and clear all elements that are being tracked on scroll.

Not as granular as I would like the script to be since that would require a whole rewrite that can happen in the future, but for now this should work for your use case.

Happy holidays 🎉

**Comment by axelhzf** [comment]
Thank you!

Happy holidays

**Comment by jeremenichelli** [comment]
@axelhzf don't know if this is an issue still for you, but a new version was released for this library where you can create an observer on `componentDidMount` and _disconnect_ it on _componentWillUnmount_ which might produce cleaner isolation and results.

Also, I'm about to create a proper React wrapper for this so stay tuned!
