### ISSUE TITLE
Page depth change without scroll event = issue

### ISSUE THREAD

**Issue by SemanticMikeG** [jeremenichelli/hunt#15]
Hi. I have a problem - I am filtering a listing, causing a containing div to resize, which brings 'hunted' elements into the viewport.  The lack of scroll event means that Hunt doesn't update.  Is there anyway I can invoke a Hunt 'update/refresh' programmatically, as I don't want to have to scroll the page? May thanks, Mike

**Comment by jeremenichelli** [comment]
Hi Mike, the internal method is not exposed but it can be easily added.

I'll try to update it today and let you know on this issue.

Thanks for reporting.

**Comment by SemanticMikeG** [comment]
Brilliant. Thank you so much!

**Comment by jeremenichelli** [comment]
@SemanticMikeG a patch has been released covering this, you can call `hunt.trigger()` and will go through all the elements buffered and check if some have become visible.

Not recommending to call this too often if you have tons of element, but at least it should cover your case. Let me know if you run into performance issues.

Cheers!

**Comment by SemanticMikeG** [comment]
That's great. Thanks very much. I'll test with it tomorrow.
All the best,
Mike

**Comment by SemanticMikeG** [comment]
Hi Jeremias,

This patch is working perfectly for me - thanks so much.

Is there any way to get this updated version into Bower so I can get it out to the rest of my dev team?

Many thanks,
Mike

**Comment by jeremenichelli** [comment]
Completely forgot about that, @SemanticMikeG the patch is now available in **bower**.
