### ISSUE TITLE
Suggestion: adding bower.json

### ISSUE THREAD

**Issue by yksikaksikolme** [jeremenichelli/hunt#6]
Hi and thank you for this great project.

My experience advises me to ask before making any effort in contributing such thing.
Many authors are strongly against adding a bower.json to their projects, however. I know bower.json is not an optimal solution for 99% of the projects using it. It's only for the laziness. 
The only argument against it worth mentioning are the costs of updating the version number in the json file.

I can't change the workflow that much in some old projects I would like to use hunt, so: Would you allow to add a bower.json?

Thank you

**Comment by jeremenichelli** [comment]
Hi there, I don't add it by default because I feel like bower is slowly dying, but I guess a `bower.json` file won't hurt. If you really need it you can do a Pull Request to add it and I'll review it.

**Comment by yksikaksikolme** [comment]
Thank you. I agree with your assumption that a bower.json doesn't hurt anyone. A Pull Request will follow.
