### ISSUE TITLE
IE9-11

### ISSUE THREAD

**Issue by kilianf** [jeremenichelli/hunt#9]
Hey Jeremias - 

You did a great job with this plugin, and I think it's the best out there for scroll detection. I've built out my site using it, and started testing, and that's when I ran into an issue in IE. The issue is that on Chrome, Safari, Firefox, when an element comes into view at the bottom it fires properly, but on IE 9-11 on Windows 7, it only fires when the element hits the top of the viewport (when it's about to go out of view). I've tested it with your demo page as well as mine, and I get the same behavior.

Any updates you might have would be greatly appreciated!

- Kilian

**Comment by jeremenichelli** [comment]
Thanks for reporting this @kilianf! As soon as I can run some test in a Windows machine I'll come back with some feedback.

**Comment by jeremenichelli** [comment]
@kilianf bug detected :bug:, will work on a fix over the weekend!

**Comment by kilianf** [comment]
That's great to hear, I really appreciate your work on this!

**Comment by jeremenichelli** [comment]
@kilianf, good news for you, there's a new version with all this problem solved. Please confirm that you're not experiencing this issue anymore so I feel sure this can be closed.

_Note: Take in count test pages won't work in IE9 since they use classList which is not supported there. _

**Comment by kilianf** [comment]
Thanks @jeremenichelli - this works perfect, and thanks again for the quick response! It saved a ton of time on a big project.

**Comment by jeremenichelli** [comment]
More than happy to read that, feel free to share your project using **hunt** when is ready!

**Comment by kilianf** [comment]
Just made the page live - http://www.uw.edu/boundless/alternative-spring-break
Hunt helped so much with dynamically loading the videos at the bottom, and with firing the animations!

**Comment by jeremenichelli** [comment]
Wow! Awesome @kilianf! Beautiful site and great use case for the script. Thanks a lot for sharing!
